version: '3.10'

services:
  sandkasten:
    image: ghcr.io/defelo/sandkasten
    restart: always
    init: true
    privileged: true
    environment:
      RUST_LOG: info,sandkasten=debug
    volumes:
      - ./config.toml:/config.toml:ro
    tmpfs:
      - /jobs
      - /programs:exec
    ports:
      - 127.0.0.1:8000:8000
